version: '2'

services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - db-volume:/home/flask/app/web/instance/dbfiles
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port 8000



volumes:
  db-volume:

